### ISSUE TITLE
Broken. Error pasted

### ISSUE THREAD

**Issue by STashakkori** [minauteur/supertroupers#29]
error[E0423]: expected function, tuple struct or tuple variant, found struct `ast::Name`

registry/src/github.com-1ecc6299db9ec823/syntex_syntax-0.54.0/src/symbol.rs:146:27    
   |
146 |                       name: ast::Name($index),
    |                             ^^^^^^^^^
...
165 | / declare_keywords! {
166 | |     // Invalid identifier
167 | |     (0,  Invalid,        "")
168 | |
...   |
231 | |     (56, CrateRoot, "{{root}}")
232 | | }
    | |_- in this macro invocation

**Comment by minauteur** [comment]
When did you receive this error? What command were you running, and with what version of rust?
I know this is two years late, but please feel free to re-open the issue with that information if you are still experiencing the error.
